/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    domains: [
      'upload.wikimedia.org',
      'images.drive.com.au',
      'mir-s3-cdn-cf.behance.net',
      'logodownload.org',
      'tequipment-finder.porsche.com',
      'files.porsche.com',
      'i.pinimg.com',
      'www.mansory.com',
      'supercarrides.com.au',
      'www.porschecenterbh.com.br',
      'mtnlimousine.com',
      'logospng.org',
      'vexstockimages.fastly.carvana.io',
      'edge.pxcrush.net',
      'www.razaoautomovel.com',
      'www.webmotors.com.br',
      'www.motorionline.com',
      'logos-world.net',
      'ecosetting-files.com',
      'www.carlogos.org',
      'www.lamborghini.com',
      'www.imagensempng.com.br',
      'www.mansory.com',
      '1000logos.net',
      'img.wallpapersafari.com',
      'vexstockimages.fastly.carvana.io',
      'mir-s3-cdn-cf.behance.net',
      'vehlogo.com',
      'mtnlimousine.com',
      'images.squarespace-cdn.com',
      'www.dimes.com',
      'ik.imagekit.io',
      'www.bmw.com.br',
    ],
  },
};

module.exports = nextConfig;
